module.exports = [
    {short:"  " , name:"(請選擇你的學系)"},
	{short:"EECS" , name:"電機資訊學士班"},
	{short:"NANO" , name:"奈米科學及工程學士學位學程"},
	{short:"EEA" , name:"電子工程學系(甲組)"},
	{short:"EEB" , name:"電子工程學系(乙組)"},
	{short:"ECEA" , name:"電機工程學系(甲組)"},
	{short:"ECEB" , name:"電機工程學系(乙組)"},
	{short:"IEO" , name:"光電工程學系"},
	{short:"CSA" , name:"資訊工程學系資電工程組"},
	{short:"CSB" , name:"資訊工程學系資訊工程組"},
	{short:"CSC" , name:"資訊工程學系網路與多媒體工程組"},
	{short:"MSE" , name:"材料科學與工程學系"},
	{short:"ME" , name:"機械工程學系"},
	{short:"CV" , name:"土木工程學系"},
	{short:"ISDPA" , name:"理學院科學學士學位學程(乙組)"},
	{short:"ISDPB" , name:"理學院科學學士學位學程(丙組)"},
	{short:"ISDPC" , name:"理學院科學學士學位學程(丁組，科學人才不分系)"},
	{short:"EPA" , name:"電子物理學系光電與奈米科學組"},
	{short:"EPB" , name:"電子物理學系電子物理組"},
	{short:"AC" , name:"應用化學系"},
	{short:"AM" , name:"應用數學系"},
	{short:"BIO" , name:"生物科技學系"},
	{short:"IMFA" , name:"資訊管理與財務金融學系資訊管理組"},
	{short:"IMFB" , name:"資訊管理與財務金融學系財務金融組"},
	{short:"MS" , name:"管理科學系"},
	{short:"TLM " , name:"運輸與物流管理學系"},
	{short:"IEM" , name:"工業工程與管理學系"},
	{short:"FL" , name:"外國語文學系"},
	{short:"CT" , name:"傳播與科技學系"},
	{short:"HS" , name:"人文社會學系"},
]
