module.exports = [
	{short:"EECS" , name:"Bachelor of Electrical Engineering and Computer classes "},
	{short:"NANO" , name:"Nano Science and Engineering Undergraduate Program "},
	{short:"EEA" , name:"Electronic Engineering (Group A) "},
	{short:"EEB" , name:"Electronic Engineering (Group B) "},
	{short:"ECEA" , name:"Department of Electrical Engineering (Group A) "},
	{short:"ECEB" , name:"Department of Electrical Engineering (Group B) "},
	{short:"IEO" , name:"Department of Photonics"},
	{short:"CSA" , name:"Information Engineering owned electrical engineering group "},
	{short:"CSB" , name:"Department of Computer Science and Information Engineering Group "},
	{short:"CSC" , name:"Department of Computer Science Engineering, Networking and Multimedia Group "},
	{short:"MSE" , name:"Department of Materials Science and Engineering "},
	{short:"ME" , name:"Department of Mechanical Engineering "},
	{short:"CV" , name:"Department of Civil Engineering "},
	{short:"ISDPA" , name:"Interdisciplinary Science Degree Program (Group B) "},
	{short:"ISDPB" , name:"Interdisciplinary Science Degree Program (Group C) "},
	{short:"ISDPC" , name:"Interdisciplinary Science Degree Program (Group D) "},
	{short:"EPA" , name:"Electronic Optical Physics and Nano Science Group "},
	{short:"EPB" , name:"Electronic Physics Department of Electronic Physics Group "},
	{short:"AC" , name:"Department of Applied Chemistry "},
	{short:"AM" , name:"Department of Applied Mathematics "},
	{short:"BIO" , name:"Department of Biotechnology "},
	{short:"IMFA" , name:"Department of Finance and Information Management Information Management Group "},
	{short:"IMFB" , name:"Information Management and Department of Finance Finance Group "},
	{short:"MS" , name:"Department of Management Science "},
	{short:"TLM" , name:"Transportation and Logistics Management "},
	{short:"IEM" , name:"Industrial Engineering and Management "},
	{short:"FL" , name:"Department of Foreign Languages "},
	{short:"CT" , name:"Department of Communication and Technology "},
	{short:"HS" , name:"Department of Humanities and Social Sciences"},
]