
module.exports = [
    {short:"  " , name:"(請選擇你的學系)"},
	{short:"EECS" , name:"電機資訊學士班"},
	{short:"NANO" , name:"奈米科學及工程學士學位學程"},
	{short:"EE" , name:"電子工程學系(甲組)"},
	{short:"EE" , name:"電子工程學系(乙組)"},
	{short:"ECE" , name:"電機工程學系(甲組)"},
	{short:"ECE" , name:"電機工程學系(乙組)"},
	{short:"IEO" , name:"光電工程學系"},
	{short:"CS" , name:"資訊工程學系資電工程組"},
	{short:"CS" , name:"資訊工程學系資訊工程組"},
	{short:"CS" , name:"資訊工程學系網路與多媒體工程組"},
	{short:"MSE" , name:"材料科學與工程學系"},
	{short:"ME" , name:"機械工程學系"},
	{short:"CV" , name:"土木工程學系"},
	{short:"ISDP" , name:"理學院科學學士學位學程(乙組)"},
	{short:"ISDP" , name:"理學院科學學士學位學程(丙組)"},
	{short:"ISDP" , name:"理學院科學學士學位學程(丁組，科學人才不分系)"},
	{short:"EP" , name:"電子物理學系光電與奈米科學組"},
	{short:"EP" , name:"電子物理學系電子物理組"},
	{short:"AC" , name:"應用化學系"},
	{short:"MATH" , name:"應用數學系"},
	{short:"" , name:"生物科技學系"},
	{short:"IMF" , name:"資訊管理與財務金融學系資訊管理組"},
	{short:"IMF" , name:"資訊管理與財務金融學系財務金融組"},
	{short:"MS" , name:"管理科學系"},
	{short:"TLM " , name:"運輸與物流管理學系"},
	{short:"IEM" , name:"工業工程與管理學系"},
	{short:"FL" , name:"外國語文學系"},
	{short:"DCT" , name:"傳播與科技學系"},
	{short:"HS" , name:"人文社會學系"},

	
]